// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOisLyxhxoSvL5P3Zv5776j5y1GYD1VEE',
    appId: '1:544488593908:web:39a8d7e7301c464615c1a1',
    messagingSenderId: '544488593908',
    projectId: 'my-first-project-8de90',
    authDomain: 'my-first-project-8de90.firebaseapp.com',
    storageBucket: 'my-first-project-8de90.firebasestorage.app',
    measurementId: 'G-9T3P2TZDDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZAgJN1eVOVD8T7luEXyZ7QB7yCGgxqk',
    appId: '1:544488593908:android:f833c41fe1a6ebd515c1a1',
    messagingSenderId: '544488593908',
    projectId: 'my-first-project-8de90',
    storageBucket: 'my-first-project-8de90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrV627rSVvi0MV4mer4lgLpUuQYyliANU',
    appId: '1:544488593908:ios:822a73f37ee7175515c1a1',
    messagingSenderId: '544488593908',
    projectId: 'my-first-project-8de90',
    storageBucket: 'my-first-project-8de90.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrV627rSVvi0MV4mer4lgLpUuQYyliANU',
    appId: '1:544488593908:ios:822a73f37ee7175515c1a1',
    messagingSenderId: '544488593908',
    projectId: 'my-first-project-8de90',
    storageBucket: 'my-first-project-8de90.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOisLyxhxoSvL5P3Zv5776j5y1GYD1VEE',
    appId: '1:544488593908:web:514e33ef4c5bb0ea15c1a1',
    messagingSenderId: '544488593908',
    projectId: 'my-first-project-8de90',
    authDomain: 'my-first-project-8de90.firebaseapp.com',
    storageBucket: 'my-first-project-8de90.firebasestorage.app',
    measurementId: 'G-10BRPT9HBG',
  );
}
